import AppLayout from '@/layouts/app-layout';
import { type BreadcrumbItem } from '@/types';
import { Head, router, useForm } from '@inertiajs/react';
import { useState } from 'react';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { AlertCircle } from 'lucide-react';

const breadcrumbs: BreadcrumbItem[] = [
  {
    title: 'Product Categories',
    href: '/product-categories',
  },
  {
    title: 'Create',
    href: '/product-categories/create',
  },
];

export default function Create() {
  const { data, setData, post, processing, errors } = useForm({
    name: '',
    slug: '',
    description: '',
  });

  const [slugAutogenerated, setSlugAutogenerated] = useState(true);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    post('/product-categories', {
      onSuccess: () => {
        // Redirect handled by the controller
      },
    });
  };

  const generateSlug = (name: string) => {
    return name
      .toLowerCase()
      .replace(/[^\w\s-]/g, '') // Remove special characters
      .replace(/\s+/g, '-') // Replace spaces with hyphens
      .replace(/-+/g, '-') // Replace multiple hyphens with a single one
      .trim();
  };

  const handleNameChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const name = e.target.value;
    setData('name', name);
    
    // Only auto-generate slug if user hasn't manually edited it
    if (slugAutogenerated) {
      setData('slug', generateSlug(name));
    }
  };

  const handleSlugChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setSlugAutogenerated(false);
    setData('slug', e.target.value);
  };

  return (
    <AppLayout breadcrumbs={breadcrumbs}>
      <Head title="Create Product Category" />
      <div className="flex h-full flex-1 flex-col gap-4 rounded-xl p-4">
        <div className="border-sidebar-border/70 dark:border-sidebar-border relative min-h-[100vh] flex-1 overflow-hidden rounded-xl border p-6 md:min-h-min">
          <div className="mx-auto max-w-2xl">
            <h1 className="text-2xl font-bold tracking-tight mb-6">Create Product Category</h1>
            
            <form onSubmit={handleSubmit}>
              <Card>
                <CardHeader>
                  <CardTitle>Category Information</CardTitle>
                  <CardDescription>
                    Create a new product category to organize your products.
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="space-y-2">
                    <Label htmlFor="name">Name</Label>
                    <Input
                      id="name"
                      value={data.name}
                      onChange={handleNameChange}
                      placeholder="Enter category name"
                    />
                    {errors.name && (
                      <Alert variant="destructive" className="py-2 mt-1">
                        <AlertCircle className="h-4 w-4" />
                        <AlertDescription>{errors.name}</AlertDescription>
                      </Alert>
                    )}
                  </div>
                  
                  <div className="space-y-2">
                    <Label htmlFor="slug">Slug</Label>
                    <Input
                      id="slug"
                      value={data.slug}
                      onChange={handleSlugChange}
                      placeholder="enter-category-slug"
                    />
                    {errors.slug && (
                      <Alert variant="destructive" className="py-2 mt-1">
                        <AlertCircle className="h-4 w-4" />
                        <AlertDescription>{errors.slug}</AlertDescription>
                      </Alert>
                    )}
                    <p className="text-sm text-gray-500">
                      The slug is used in the URL and should be unique.
                    </p>
                  </div>
                  
                  <div className="space-y-2">
                    <Label htmlFor="description">Description (Optional)</Label>
                    <Textarea
                      id="description"
                      value={data.description}
                      onChange={(e) => setData('description', e.target.value)}
                      placeholder="Enter category description"
                      rows={4}
                    />
                    {errors.description && (
                      <Alert variant="destructive" className="py-2 mt-1">
                        <AlertCircle className="h-4 w-4" />
                        <AlertDescription>{errors.description}</AlertDescription>
                      </Alert>
                    )}
                  </div>
                </CardContent>
                <CardFooter className="flex justify-between">
                  <Button 
                    type="button" 
                    variant="outline"
                    onClick={() => router.visit('/product-categories')}
                  >
                    Cancel
                  </Button>
                  <Button type="submit" disabled={processing}>
                    {processing ? 'Creating...' : 'Create Category'}
                  </Button>
                </CardFooter>
              </Card>
            </form>
          </div>
        </div>
      </div>
    </AppLayout>
  );
}
